name: Run Python Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can change this version
        username: 'Amit'
        greeting: 'Hi'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        #pip install -r requirements.txt  # Optional, if you have dependencies

    - name: Run Python script
      run: |
        python myworkflowscript.py  # Replace with your script name
        python downloadbin.py

        
